// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// 🔒 SECURITY NOTE: API keys in this file are CLIENT-SIDE PUBLIC KEYS.
// These keys are safe to commit because:
// - They are bundled into your app and visible to users
// - They are restricted by domain/bundle ID in Firebase Console
// - They cannot access your Firebase project without proper authentication
// - This is standard practice for FlutterFire applications
//
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import '../common/constants/environment_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: EnvironmentConfig.firebaseWebApiKey,
        appId: EnvironmentConfig.firebaseWebAppId,
        messagingSenderId: EnvironmentConfig.firebaseMessagingSenderId,
        projectId: EnvironmentConfig.firebaseProjectId,
        authDomain: EnvironmentConfig.firebaseAuthDomain,
        storageBucket: EnvironmentConfig.firebaseStorageBucket,
        measurementId: EnvironmentConfig.firebaseWebMeasurementId,
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: EnvironmentConfig.firebaseAndroidApiKey,
        appId: EnvironmentConfig.firebaseAndroidAppId,
        messagingSenderId: EnvironmentConfig.firebaseMessagingSenderId,
        projectId: EnvironmentConfig.firebaseProjectId,
        storageBucket: EnvironmentConfig.firebaseStorageBucket,
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: EnvironmentConfig.firebaseIosApiKey,
        appId: EnvironmentConfig.firebaseIosAppId,
        messagingSenderId: EnvironmentConfig.firebaseMessagingSenderId,
        projectId: EnvironmentConfig.firebaseProjectId,
        storageBucket: EnvironmentConfig.firebaseStorageBucket,
        iosBundleId: EnvironmentConfig.bundleId,
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: EnvironmentConfig.firebaseMacosApiKey,
        appId: EnvironmentConfig.firebaseMacosAppId,
        messagingSenderId: EnvironmentConfig.firebaseMessagingSenderId,
        projectId: EnvironmentConfig.firebaseProjectId,
        storageBucket: EnvironmentConfig.firebaseStorageBucket,
        iosBundleId: EnvironmentConfig.bundleId,
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: EnvironmentConfig.firebaseWindowsApiKey,
        appId: EnvironmentConfig.firebaseWindowsAppId,
        messagingSenderId: EnvironmentConfig.firebaseMessagingSenderId,
        projectId: EnvironmentConfig.firebaseProjectId,
        authDomain: EnvironmentConfig.firebaseAuthDomain,
        storageBucket: EnvironmentConfig.firebaseStorageBucket,
        measurementId: EnvironmentConfig.firebaseWindowsMeasurementId,
      );
}
