// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// 🔒 SECURITY NOTE: API keys in this file are CLIENT-SIDE PUBLIC KEYS.
// These keys are safe to commit because:
// - They are bundled into your app and visible to users
// - They are restricted by domain/bundle ID in Firebase Console
// - They cannot access your Firebase project without proper authentication
// - This is standard practice for FlutterFire applications
//
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArl95qqaPZNtT2_NVg9sY15t06zq5h6dg',
    appId: '1:665010238088:web:4ab7c29b9112469119a53d',
    messagingSenderId: '665010238088',
    projectId: 'atitia-87925',
    authDomain: 'atitia-87925.firebaseapp.com',
    storageBucket: 'atitia-87925.firebasestorage.app',
    measurementId: 'G-SBS8EXZF76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWFaZgLfoGlJeLIrLNK_d9xFuYfqp6XtQ',
    appId: '1:665010238088:android:27a01be236b0ad9d19a53d',
    messagingSenderId: '665010238088',
    projectId: 'atitia-87925',
    storageBucket: 'atitia-87925.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzEcqX-xF7EqTWsrqkF0mihRdwBRxUZA8',
    appId: '1:665010238088:ios:76437d681978a96019a53d',
    messagingSenderId: '665010238088',
    projectId: 'atitia-87925',
    storageBucket: 'atitia-87925.firebasestorage.app',
    iosBundleId: 'com.avishio.atitia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzEcqX-xF7EqTWsrqkF0mihRdwBRxUZA8',
    appId: '1:665010238088:ios:76437d681978a96019a53d',
    messagingSenderId: '665010238088',
    projectId: 'atitia-87925',
    storageBucket: 'atitia-87925.firebasestorage.app',
    iosBundleId: 'com.avishio.atitia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArl95qqaPZNtT2_NVg9sY15t06zq5h6dg',
    appId: '1:665010238088:web:128b16317971fd2819a53d',
    messagingSenderId: '665010238088',
    projectId: 'atitia-87925',
    authDomain: 'atitia-87925.firebaseapp.com',
    storageBucket: 'atitia-87925.firebasestorage.app',
    measurementId: 'G-CMR3GYQ8GB',
  );
}
