// lib/main.dart

import 'package:atitia/common/services/environment_validation_service.dart';
import 'package:atitia/common/utils/responsive/responsive_system.dart';
import 'package:atitia/core/app/info/app_info.dart';
import 'package:atitia/core/app/localization/locale_provider.dart';
import 'package:atitia/core/app/localization/localization_setup.dart';
import 'package:atitia/core/app/theme/theme_provider.dart';
import 'package:atitia/core/di/firebase/start/firebase_service_initializer.dart';
import 'package:atitia/core/navigation/app_router.dart';
import 'package:atitia/core/providers/firebase/firebase_app_providers.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import 'core/app/emergency/emergency_fallback_app.dart';

/// Application entry point with clean, modern architecture
Future<void> main() async {
  // Ensure Flutter binding is initialized first
  WidgetsFlutterBinding.ensureInitialized();

  // Performance optimizations
  WidgetsBinding.instance.scheduleFrameCallback((_) {
    // Pre-warm critical services for faster app startup
  });

  // Frame rate optimization - limit to 60fps to reduce buffer queue pressure
  WidgetsBinding.instance.addPostFrameCallback((_) {
    // Enable smooth scrolling and reduce unnecessary repaints
  });

  try {
    // Validate environment configuration first
    final isValidEnvironment =
        await EnvironmentValidationService.validateEnvironment();
    if (!isValidEnvironment) {
      // Continue anyway for development, but log the issue
    }

    // Print environment summary
    EnvironmentValidationService.printEnvironmentSummary();

    // Single initialization call - handles everything
    await FirebaseServiceInitializer.initialize();

    // Initialize responsive system
    ResponsiveSystem.initialize();

    // Create LocaleProvider and load saved locale preference
    final localeProvider = LocaleProvider();
    await localeProvider.loadLocale();

    // Start the app with all providers and services ready
    runApp(
      FirebaseAppProviders.buildWithProviders(
        localeProvider: localeProvider,
        child: const AtitiaApp(),
      ),
    );
  } catch (error) {
    // Handle critical initialization failures gracefully

    /// 🚨 EMERGENCY FALLBACK APPLICATION
    // Fallback to emergency UI - users always see something
    runApp(const EmergencyFallbackApp());
  }
}

/// 🎯 ROOT APPLICATION WIDGET
/// Main application with theme, localization, and provider configuration
class AtitiaApp extends StatelessWidget {
  const AtitiaApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Consumer2<ThemeProvider, LocaleProvider>(
      builder: (context, themeProvider, localeProvider, child) {
        return MaterialApp.router(
          // App Info
          debugShowCheckedModeBanner: AppInfo.showDebugBanner,
          restorationScopeId: AppInfo.restorationScopeId,
          title: AppInfo.appTitle,

          // Theme Configuration
          theme: themeProvider.lightTheme,
          darkTheme: themeProvider.darkTheme,
          themeMode: themeProvider.themeMode,

          // Localization Configuration
          locale: localeProvider.locale,
          supportedLocales: LocalizationSetup.supportedLocales,
          localizationsDelegates: LocalizationSetup.delegates,

          // Router Configuration (GoRouter)
          routerConfig: AppRouter.router,

          // Performance optimizations and responsive system
          builder: (context, child) {
            // Add performance monitoring and responsive system
            return ResponsiveSystemProvider(
              child: MediaQuery(
                data: MediaQuery.of(context).copyWith(
                  // Limit frame rate to reduce buffer queue pressure
                  devicePixelRatio:
                      MediaQuery.of(context).devicePixelRatio.clamp(1.0, 3.0),
                ),
                child: child!,
              ),
            );
          },
        );
      },
    );
  }
}

/*
Short answer: not yet.
Telugu is only superficially “100 %” because we backfilled missing keys with the English text. Many UI surfaces will still show English for Telugu users, so the store review will see a bilingual experience.
We’ve touched a large set of files already. Before shipping, you should complete the actual Telugu translations and run a full sanity sweep (QA in both locales, golden updates, accessibility checks, release build smoke, etc.).
Also revise the Play Store collateral (screenshots, listing copy) to reflect both languages once translation work is done.
Once the translations are real and you’ve run your pre-release checklist, you’ll be safer to submit. Let me know when you want to plan the final readiness pass.
*/
/*

AppLocalizations
Generated by Flutter’s gen-l10n.
Requires a BuildContext.
Perfect for widgets and any code running inside the widget tree.
Gives you type-safe getters plus ICU plural/parameter helpers.
InternationalizationService.translate()
Our custom context-free wrapper.
Doesn’t need a widget or BuildContext.
Used in places like view models, repositories, service layers, analytics/logging—anywhere UI context isn’t available.
Falls back to the English string if a key is missing so background logic doesn’t crash.
So we use AppLocalizations.of(context) when we’re in UI code, and _i18n.translate(...) when we’re outside the widget tree and still need localized copy.
*/
