#!/bin/bash
# ==================================================
# 🔐 ANDROID SIGNING SETUP
# ==================================================
# Generate keystore, configure signing, and inject env vars
# Usage: bash scripts/android_sign.sh [action]
# Actions: generate, configure, verify (default: configure)

set -e

# Source environment setup
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS_ROOT="$(cd "$SCRIPT_DIR/.." source "$SCRIPT_DIR/setup_env.sh"source "$SCRIPT_DIR/setup_env.sh" pwd)"
source "$SCRIPTS_ROOT/core/setup_env.sh"

ACTION="${1:-configure}"

# Generate keystore
generate_keystore() {
    echo "🔑 Generating Android keystore..."
    
    if [ -z "$ANDROID_KEYSTORE_PASSWORD" ] || [ -z "$ANDROID_KEY_PASSWORD" ]; then
        echo "❌ ANDROID_KEYSTORE_PASSWORD and ANDROID_KEY_PASSWORD must be set"
        echo "   Set them in .secrets/common/.env"
        exit 1
    fi
    
    if [ -f "$ANDROID_KEYSTORE_PATH" ]; then
        echo "⚠️  Keystore already exists at $ANDROID_KEYSTORE_PATH"
        read -p "   Overwrite? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo "❌ Aborted"
            exit 1
        fi
    fi
    
    keytool -genkey -v \
        -keystore "$ANDROID_KEYSTORE_PATH" \
        -alias "${ANDROID_KEY_ALIAS:-atitia-release}" \
        -keyalg RSA \
        -keysize 2048 \
        -validity 10000 \
        -storepass "$ANDROID_KEYSTORE_PASSWORD" \
        -keypass "$ANDROID_KEY_PASSWORD" \
        -dname "CN=Atitia, OU=Development, O=Charyatani, L=City, ST=State, C=IN"
    
    echo "✅ Keystore generated at $ANDROID_KEYSTORE_PATH"
}

# Configure signing
configure_signing() {
    echo "⚙️  Configuring Android signing..."
    
    if [ ! -f "$ANDROID_KEYSTORE_PATH" ]; then
        echo "❌ Keystore not found at $ANDROID_KEYSTORE_PATH"
        echo "   Run: bash scripts/android_sign.sh generate"
        exit 1
    fi
    
    # Create key.properties file
    KEY_PROPERTIES="$PROJECT_ROOT/android/key.properties"
    cat > "$KEY_PROPERTIES" << EOF
# Android Production Signing Configuration
# Auto-generated by android_sign.sh
# DO NOT COMMIT THIS FILE TO GIT

storeFile=$(basename "$ANDROID_KEYSTORE_PATH")
storePassword=$ANDROID_KEYSTORE_PASSWORD
keyAlias=$ANDROID_KEY_ALIAS
keyPassword=$ANDROID_KEY_PASSWORD
EOF
    
    # Copy keystore to android directory if not already there
    KEYSTORE_DEST="$PROJECT_ROOT/android/$(basename "$ANDROID_KEYSTORE_PATH")"
    if [ "$ANDROID_KEYSTORE_PATH" != "$KEYSTORE_DEST" ]; then
        if [ ! -f "$KEYSTORE_DEST" ]; then
            cp "$ANDROID_KEYSTORE_PATH" "$KEYSTORE_DEST"
            echo "📋 Keystore copied to android directory"
        fi
    fi
    
    # Update build.gradle.kts to use key.properties
    BUILD_GRADLE="$PROJECT_ROOT/android/app/build.gradle.kts"
    if [ -f "$BUILD_GRADLE" ]; then
        echo "✅ Signing configured in build.gradle.kts"
        echo "   Make sure build.gradle.kts references key.properties"
    fi
    
    echo "✅ Android signing configuration complete"
    echo "   Keystore: $ANDROID_KEYSTORE_PATH"
    echo "   Properties: $KEY_PROPERTIES"
}

# Verify signing setup
verify_signing() {
    echo "🔍 Verifying Android signing setup..."
    
    local errors=0
    
    if [ ! -f "$ANDROID_KEYSTORE_PATH" ]; then
        echo "❌ Keystore not found: $ANDROID_KEYSTORE_PATH"
        errors=$((errors + 1))
    else
        echo "✅ Keystore found"
    fi
    
    KEY_PROPERTIES="$PROJECT_ROOT/android/key.properties"
    if [ ! -f "$KEY_PROPERTIES" ]; then
        echo "❌ key.properties not found: $KEY_PROPERTIES"
        errors=$((errors + 1))
    else
        echo "✅ key.properties found"
    fi
    
    if [ -z "$ANDROID_KEYSTORE_PASSWORD" ]; then
        echo "⚠️  ANDROID_KEYSTORE_PASSWORD not set"
        errors=$((errors + 1))
    else
        echo "✅ Keystore password configured"
    fi
    
    if [ $errors -eq 0 ]; then
        echo "✅ Android signing setup verified"
    else
        echo "❌ Found $errors issue(s)"
        exit 1
    fi
}

# Execute action
case $ACTION in
    generate)
        generate_keystore
        ;;
    configure)
        configure_signing
        ;;
    verify)
        verify_signing
        ;;
    *)
        echo "❌ Unknown action: $ACTION"
        echo "   Usage: bash scripts/android_sign.sh [generate|configure|verify]"
        exit 1
        ;;
esac

