#!/bin/bash

# Android Production Signing Setup Script
# This script helps you generate a keystore for Android release builds

echo "🔐 Android Production Signing Setup"
echo "===================================="
echo ""

# Check if keystore already exists
if [ -f "android/keystore.jks" ]; then
    echo "⚠️  Keystore already exists at android/keystore.jks"
    read -p "Do you want to create a new one? (y/N): " create_new
    if [[ ! $create_new =~ ^[Yy]$ ]]; then
        echo "Exiting. Using existing keystore."
        exit 0
    fi
fi

echo "This will create a new Android signing keystore."
echo "⚠️  IMPORTANT: Keep this keystore file and passwords safe!"
echo "   You'll need them for all future app updates."
echo ""

# Get keystore details
read -p "Enter keystore password: " -s store_password
echo ""
read -p "Confirm keystore password: " -s store_password_confirm
echo ""

if [ "$store_password" != "$store_password_confirm" ]; then
    echo "❌ Passwords don't match. Exiting."
    exit 1
fi

read -p "Enter key alias [atitia-release]: " key_alias
key_alias=${key_alias:-atitia-release}

read -p "Enter key password [Press Enter to use same as keystore]: " -s key_password
echo ""
if [ -z "$key_password" ]; then
    key_password=$store_password
fi

read -p "Enter your name (for certificate): " name
read -p "Enter your organization unit [Development]: " org_unit
org_unit=${org_unit:-Development}
read -p "Enter your organization [Atitia]: " organization
organization=${organization:-Atitia}
read -p "Enter city [Your City]: " city
read -p "Enter state [Your State]: " state
read -p "Enter country code (2 letters) [IN]: " country
country=${country:-IN}

echo ""
echo "Generating keystore..."

keytool -genkey -v \
  -keystore android/keystore.jks \
  -keyalg RSA \
  -keysize 2048 \
  -validity 10000 \
  -alias "$key_alias" \
  -storepass "$store_password" \
  -keypass "$key_password" \
  -dname "CN=$name, OU=$org_unit, O=$organization, L=$city, ST=$state, C=$country"

if [ $? -eq 0 ]; then
    echo ""
    echo "✅ Keystore created successfully at android/keystore.jks"
    echo ""
    
    # Create key.properties file
    cat > android/key.properties << EOF
# Android Production Signing Configuration
# Generated by setup-android-signing.sh
# DO NOT COMMIT THIS FILE TO GIT

storeFile=keystore.jks
storePassword=$store_password
keyAlias=$key_alias
keyPassword=$key_password
EOF
    
    echo "✅ Created android/key.properties"
    echo ""
    echo "⚠️  IMPORTANT NEXT STEPS:"
    echo "1. Add android/key.properties to .gitignore"
    echo "2. Backup android/keystore.jks to a secure location"
    echo "3. Store passwords in a password manager"
    echo "4. Never share these files or commit them to git!"
    echo ""
    echo "✅ Setup complete! You can now build release APKs/AABs."
else
    echo ""
    echo "❌ Failed to create keystore. Please check the errors above."
    exit 1
fi

